var mongoose = require("mongoose");

var FeatSchema = new mongoose.Schema({
   name: {type: String, required: true},
   type: {type: String, required: true},
   description: {type: String},
   prerequisite_feats: {type: String},
   benefit: {type: String, required: true},
   normal: {type: String},
   special: {type: String},
   source: {type: String, required: true},
   fulltext: {type: String, required: true},
   teamwork: {type: Number, required: true},
   critical: {type: Number, required: true},
   grit: {type: Number, required: true},
   style: {type: Number, required: true},
   performance: {type: Number, required: true},
   racial: {type: Number, required: true},
   companion_familiar: {type: Number, required: true},
   race_name: {type: String},
   note: {type: String},
   goal: {type: String},
   completion_benefit: {type: String},
   multiples: {type: Number, required: true},
   suggested_traits: {type: String},
   prerequisite_skills: {type: String},
   panache: {type: Number, required: true},
   betrayal: {type: Number, required: true},
   targeting: {type: Number, required: true},
   esoteric: {type: Number, required: true},
   stare: {type: Number, required: true},
   weapon_mastery: {type: Number, required: true},
   item_mastery: {type: Number, required: true},
   armor_mastery: {type: Number, required: true},
   shield_mastery: {type: Number, required: true},
});
mongoose.model("Feat", FeatSchema);